# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gts28wifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/bcm4356A2_V0046.0000.hcd:system/vendor/firmware/bcm4356A2_V0046.0000.hcd \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/bcm4358A1_V0041.0073.hcd:system/vendor/firmware/bcm4358A1_V0041.0073.hcd \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/bcm4358A3_V0036.0055.hcd:system/vendor/firmware/bcm4358A3_V0036.0055.hcd \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/nvram_mfg.txt_4356_a2:system/etc/wifi/nvram_mfg.txt_4356_a2 \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/nvram_mfg.txt_4358_a1:system/etc/wifi/nvram_mfg.txt_4358_a1 \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/nvram_net.txt_4356_a2:system/etc/wifi/nvram_net.txt_4356_a2 \
    vendor/samsung/gts28wifi/proprietary/etc/wifi/nvram_net.txt_4358_a1:system/etc/wifi/nvram_net.txt_4358_a1 \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/hevc_fw.bin:system/vendor/firmware/hevc_fw.bin \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/fimc_is_fw2_4h5.bin:system/vendor/firmware/fimc_is_fw2_4h5.bin \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/seiren_fw_dram.bin:system/vendor/firmware/seiren_fw_dram.bin \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/seiren_fw_sram.bin:system/vendor/firmware/seiren_fw_sram.bin \
    vendor/samsung/gts28wifi/proprietary/lib/hw/audio.primary.universal5433.so:system/lib/hw/audio.primary.universal5433.so \
    vendor/samsung/gts28wifi/proprietary/lib/libExynosHWCService.so:system/lib/libExynosHWCService.so \
    vendor/samsung/gts28wifi/proprietary/lib/libSamsungPostProcess.so:system/lib/libSamsungPostProcess.so \
    vendor/samsung/gts28wifi/proprietary/lib/libSamsungPostProcess.so:system/lib/libSamsungPostProcess.so \
    vendor/samsung/gts28wifi/proprietary/lib/libSamsungPostProcessConvertor.so:system/lib/libSamsungPostProcessConvertor.so \
    vendor/samsung/gts28wifi/proprietary/lib/libSamsungPreProcess.so:system/lib/libSamsungPreProcess.so \
    vendor/samsung/gts28wifi/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/gts28wifi/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/gts28wifi/proprietary/lib/libpreprocessing_nxp.so:system/lib/libpreprocessing_nxp.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsamsungDiamondVoiceExt.so:system/lib/libsamsungDiamondVoiceExt.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/gts28wifi/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/samsung/gts28wifi/proprietary/lib/libvirtualdisplay.so:system/lib/libvirtualdisplay.so \
    vendor/samsung/gts28wifi/proprietary/lib/libvirtualdisplaymodule.so:system/lib/libvirtualdisplaymodule.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsamsungSoundbooster_ext.so:system/lib/libsamsungSoundbooster_ext.so \
    vendor/samsung/gts28wifi/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
    vendor/samsung/gts28wifi/proprietary/lib/lib_SoundBooster_ver609a.so:system/lib/lib_SoundBooster_ver609a.so \
    vendor/samsung/gts28wifi/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:system/lib/lib_SoundAlive_SRC192_ver205.so \
    vendor/samsung/gts28wifi/proprietary/lib/lib_SamsungRec_V04013.so:system/lib/lib_SamsungRec_V04013.so \
    vendor/samsung/gts28wifi/proprietary/lib/lib_DNSe_NRSS_ver226.so:system/lib/lib_DNSe_NRSS_ver226.so \
    vendor/samsung/gts28wifi/proprietary/lib/hw/camera.universal5433.so:system/lib/hw/camera.universal5433.so \
    vendor/samsung/gts28wifi/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/gts28wifi/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/gts28wifi/proprietary/lib/libvdis.so:system/lib/libvdis.so \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/setfile_4h5.bin:system/vendor/firmware/setfile_4h5.bin \
    vendor/samsung/gts28wifi/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    vendor/samsung/gts28wifi/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/gts28wifi/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/libmalicore.bc:system/vendor/lib/libmalicore.bc \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/libRSDriverArm.so:system/vendor/lib/libRSDriverArm.so \
    vendor/samsung/gts28wifi/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.MP3.Decoder.so:system/lib/omx/libOMX.Exynos.MP3.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.AAC.Decoder.so:system/lib/omx/libOMX.Exynos.AAC.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/omx/libOMX.Exynos.FLAC.Decoder.so:system/lib/omx/libOMX.Exynos.FLAC.Decoder.so \
    vendor/samsung/gts28wifi/proprietary/lib/hw/sensors.exynos5.so:system/lib/hw/sensors.exynos5.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/gts28wifi/proprietary/lib/libyasalgo.so:system/lib/libyasalgo.so \
    vendor/samsung/gts28wifi/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/gts28wifi/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/gts28wifi/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/gts28wifi/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/07010000000000000000000000000000.tlbin:system//app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system//app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/07060000000000000000000000000000.tlbin:system//app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system//app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000011.tlbin:system//app/mcRegistry/ffffffff000000000000000000000011.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system//app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system//app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000021.tlbin:system//app/mcRegistry/ffffffff000000000000000000000021.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000012.tlbin:system//app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000013.tlbin:system//app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system//app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff00000000000000000000001f.tlbin:system//app/mcRegistry/ffffffff00000000000000000000001f.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system//app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000017.tlbin:system//app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000018.tlbin:system//app/mcRegistry/ffffffff000000000000000000000018.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/02010000080300030000000000000000.tlbin:system//app/mcRegistry/02010000080300030000000000000000.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000005.tlbin:system//app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000019.tlbin:system//app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/00060308060501020000000000000000.tlbin:system//app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system//app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system//app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system//app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system//app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system//app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000004.tlbin:system//app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/gts28wifi/proprietary//app/mcRegistry/ffffffff000000000000000000000016.tlbin:system//app/mcRegistry/ffffffff000000000000000000000016.tlbin
